### ISSUE TITLE
Long subject & HTML body bring error

### ISSUE THREAD

**Issue by kibi** [jpscaletti/MailShake#5]
If you create message with HTML body and long subject:
```
    email_msg = EmailMessage(
        subject='Rather long subject ............................................................................',
        html='<h1>html message body</h1>'
        from_email='test@test.com',
        to='my@test.com'
    )
```

It causes to error while sending the message:
Traceback (most recent call last):
  File "C:\Users\ ___\lib\site-packages\mailshake\mailers\smtp.py", line 111, in send_messages
    sent = self._send(message)
  File "C:\Users\ ___\lib\site-packages\mailshake\mailers\smtp.py", line 136, in _send
    self.connection.sendmail(from_email, group, message.as_bytes())
  File "C:\Users\ ___\lib\site-packages\mailshake\message.py", line 199, in as_bytes
    return self.render().as_bytes(unixfrom)
  File "C:\Users\ ___\lib\site-packages\mailshake\message.py", line 167, in render
    msg['Subject'] = self.subject
  File "C:\Users\ ___\lib\site-packages\mailshake\message.py", line 94, in __setitem__
    MIMEMultipart.__setitem__(self, name, val)
  File "C:\Program Files (x86)\Python35-32\lib\email\message.py", line 410, in __setitem__
    self._headers.append(self.policy.header_store_parse(name, val))
  File "C:\Program Files (x86)\Python35-32\lib\email\policy.py", line 138, in header_store_parse
    raise ValueError("Header values may not contain linefeed "
ValueError: Header values may not contain linefeed or carriage return characters

**Comment by sochi** [comment]
Note that the subject doesn't need to be that long to hit the issue. In fact, the encoded length matters thus using non-latin characters makes you hit the problem way sooner.

For instance using characters like `ř` would limit you to around 40 characters :-)
